"""Database operations module for SQLite interactions."""

from .operations import (
    create_audio_journal_entry,
    create_goal,
    create_goal_reminder,
    create_rating,
    create_referral,
    create_user,
    create_user_state,
    delete_goal,
    delete_user_state,
    get_all_goal_reminders,
    get_goal,
    get_goal_reminder_by_goal_id,
    get_rating_by_goal_and_date,
    get_user,
    get_user_audio_journal_entries,
    get_user_by_phone_number,
    get_user_goals,
    get_user_state,
    update_audio_journal_entry,
    update_goal_reminder,
    update_rating,
    update_user,
)
from .sqlite import connect, init_db

__all__ = [
    "connect",
    "create_audio_journal_entry",
    "create_goal",
    "create_goal_reminder",
    "create_rating",
    "create_referral",
    "create_user",
    "create_user_state",
    "delete_goal",
    "delete_user_state",
    "get_all_goal_reminders",
    "get_goal",
    "get_goal_reminder_by_goal_id",
    "get_rating_by_goal_and_date",
    "get_user",
    "get_user_audio_journal_entries",
    "get_user_by_phone_number",
    "get_user_goals",
    "get_user_state",
    "init_db",
    "update_audio_journal_entry",
    "update_goal_reminder",
    "update_rating",
    "update_user",
]
