"""Configuration module for the Flask app."""

import os

from dotenv import load_dotenv

from .api import ASSEMBLYAI_BASE_URL, OPENAI_API_URL, WHATSAPP_API_URL
from .log_setup import setup_logging
from .messages import (
    ERROR_ADD_GOAL_FIRST,
    ERROR_INVALID_DELETE_FORMAT,
    ERROR_INVALID_GOAL_NUMBER,
    ERROR_INVALID_INPUT_LENGTH,
    ERROR_INVALID_TIME_FORMAT,
    ERROR_INVALID_UPDATE_FORMAT,
    ERROR_NO_GOALS_SET,
    HELP_MESSAGE,
    JOURNAL_REMINDER_MESSAGE,
    LOOKBACK_NO_GOALS,
    REFERRAL_SUCCESS,
    REMINDER_MESSAGE,
    SUCCESS_GOAL_ADDED,
    SUCCESS_INDIVIDUAL_RATING,
    SUCCESS_JOURNALING_ENABLED,
    SUCCESS_RATINGS_SUBMITTED,
    SUCCESS_TRANSCRIPT_DISABLED,
    SUCCESS_TRANSCRIPT_ENABLED,
    USAGE_RATE,
    WELCOME_MESSAGE,
)
from .paths import ACCESS_LOG, DATABASE_FILE, ERROR_LOG, LOGS, SCHEMA_FILE
from .prompts import OPENAI_SUMMARIZATION_SYSTEM_PROMPT
from .settings import (
    COMMAND_ALIASES,
    DEFAULT_GOAL_EMOJI,
    FLASK_ENV,
    OPENAI_CHAT_MODEL,
    STYLE,
)

load_dotenv()

ASSEMBLYAI_API_KEY = os.getenv("ASSEMBLYAI_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

__all__ = [
    "ACCESS_LOG",
    "ASSEMBLYAI_API_KEY",
    "ASSEMBLYAI_BASE_URL",
    "COMMAND_ALIASES",
    "DATABASE_FILE",
    "DEFAULT_GOAL_EMOJI",
    "ERROR_ADD_GOAL_FIRST",
    "ERROR_INVALID_DELETE_FORMAT",
    "ERROR_INVALID_GOAL_NUMBER",
    "ERROR_INVALID_INPUT_LENGTH",
    "ERROR_INVALID_TIME_FORMAT",
    "ERROR_INVALID_UPDATE_FORMAT",
    "ERROR_LOG",
    "ERROR_NO_GOALS_SET",
    "FLASK_ENV",
    "HELP_MESSAGE",
    "JOURNAL_REMINDER_MESSAGE",
    "LOGS",
    "LOOKBACK_NO_GOALS",
    "OPENAI_API_KEY",
    "OPENAI_API_URL",
    "OPENAI_CHAT_MODEL",
    "OPENAI_SUMMARIZATION_SYSTEM_PROMPT",
    "REFERRAL_SUCCESS",
    "REMINDER_MESSAGE",
    "SCHEMA_FILE",
    "STYLE",
    "SUCCESS_GOAL_ADDED",
    "SUCCESS_INDIVIDUAL_RATING",
    "SUCCESS_JOURNALING_ENABLED",
    "SUCCESS_RATINGS_SUBMITTED",
    "SUCCESS_TRANSCRIPT_DISABLED",
    "SUCCESS_TRANSCRIPT_ENABLED",
    "USAGE_RATE",
    "WELCOME_MESSAGE",
    "WHATSAPP_API_URL",
    "setup_logging",
]
