"""Configuration module for the Flask app."""

from .api import ASSEMBLYAI_BASE_URL, OPENAI_API_URL, WHATSAPP_API_URL
from .logging import setup_logging
from .messages import (
    ERROR_INVALID_INPUT_LENGTH,
    ERROR_NO_GOALS_SET,
    HELP_MESSAGE,
    JOURNAL_REMINDER_MESSAGE,
    LOOKBACK_NO_GOALS,
    REFERRAL_SUCCESS,
    REMINDER_MESSAGE,
    SUCCESS_INDIVIDUAL_RATING,
    SUCCESS_RATINGS_SUBMITTED,
    USAGE_RATE,
    WELCOME_MESSAGE,
)
from .paths import ACCESS_LOG, DATABASE_FILE, ERROR_LOG, LOGS, SCHEMA_FILE
from .secrets import ASSEMBLYAI_API_KEY, OPENAI_API_KEY
from .settings import (
    COMMAND_ALIASES,
    DEFAULT_GOAL_EMOJI,
    FLASK_ENV,
    OPENAI_CHAT_MODEL,
    OPENAI_SUMMARIZATION_SYSTEM_PROMPT,
    STYLE,
)

__all__ = [
    "ACCESS_LOG",
    "ASSEMBLYAI_API_KEY",
    "ASSEMBLYAI_BASE_URL",
    "COMMAND_ALIASES",
    "DATABASE_FILE",
    "DEFAULT_GOAL_EMOJI",
    "ERROR_INVALID_INPUT_LENGTH",
    "ERROR_LOG",
    "ERROR_NO_GOALS_SET",
    "FLASK_ENV",
    "HELP_MESSAGE",
    "JOURNAL_REMINDER_MESSAGE",
    "LOGS",
    "LOOKBACK_NO_GOALS",
    "OPENAI_API_KEY",
    "OPENAI_API_URL",
    "OPENAI_CHAT_MODEL",
    "OPENAI_SUMMARIZATION_SYSTEM_PROMPT",
    "REFERRAL_SUCCESS",
    "REMINDER_MESSAGE",
    "SCHEMA_FILE",
    "STYLE",
    "SUCCESS_INDIVIDUAL_RATING",
    "SUCCESS_RATINGS_SUBMITTED",
    "USAGE_RATE",
    "WELCOME_MESSAGE",
    "WHATSAPP_API_URL",
    "setup_logging",
]
